version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\android-sdk
  AndroidSdkDirectory: C:\android-sdk

build_script:
 - cmd: mklink /j %ANDROID_HOME% "C:\Program Files (x86)\Android\android-sdk"
 - cmd: echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools,tools,android-10,android-15,android-23
 - ps: .\build.ps1
  
artifacts:
 - path: output\
 - path: output\*.*
